kind: pipeline
type: docker
name: default

steps:
  - name: npm install and build
    image: node:17
    commands:
      - |
        npm install --registry https://registry.npm.taobao.org && npm run build

  - name: transfer file to server
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: SSH_TARGET
      username:
        from_secret: SSH_USERNAME
      port: 22
      key:
        from_secret: SSH_PRIVATE_KEY
      target:
        from_secret: DEPLOY_PATH
      source: dist/*
      rm: true
  
  - name: deploy
    image: appleboy/drone-ssh
    environment:
      DEPLOY_PATH:
        from_secret: DEPLOY_PATH
    settings:
      host:
        from_secret: SSH_TARGET
      username:
        from_secret: SSH_USERNAME
      port: 22
      key:
        from_secret: SSH_PRIVATE_KEY
      envs: [DEPLOY_PATH]
      script:
        - mv $${DEPLOY_PATH}/dist/* $${DEPLOY_PATH}/ && rm -rf $${DEPLOY_PATH}/dist
        - cd $${DEPLOY_PATH}/../ && docker-compsoe restart
      
