kind: pipeline
type: docker
name: default

steps:
  - name: npm install and build
    image: node:17
    commands:
      - |
        npm install --registry https://registry.npm.taobao.org && npm run build